Add toolbar singleplayer
MuiaLeandro/duelosMeli pull request #38
Opened 2022-04-24 16:11 UTC by BrenMiRo

### Cambios realizados
- Cambia el color de fondo de toda la aplicación por blanco
- Crea include_header.xml para utilizar como toolbar (con flecha atrás y título)
- Agrega include_header.xml a los layout seteando **título y comportamiento** de la flecha al presionarla en:
   -  Todas las activities del modo de juego "**singleplayer**"
   -  A la activity "**Nuevo juego multijugador**"
### include_header.xml:
![include_header.xml](https://user-images.githubusercontent.com/79482548/164985197-3337b177-8f1f-4d2b-9fc5-93d3f39bb193.png)

2022-04-24 17:19 UTC, learanda approved these changes
Queda en "veremos" la modificación de la "," o el ")" en los observers 📄

2022-04-24 20:32 UTC, soleecito approved these changes

2022-04-24 21:57 UTC, MuiaLeandro requested changes
Parece que según la resolución de la pantalla el texto puede quedar muy cerca del borde
![image](https://user-images.githubusercontent.com/74152144/164997989-c291e900-555b-44e8-b2a4-51b62927c603.png)

Podriamos acercar el texto al icono
![image](https://user-images.githubusercontent.com/74152144/164998301-9095c8d0-09a9-488f-9407-971cf370b8ea.png)


achicarle la letra
![image](https://user-images.githubusercontent.com/74152144/164998204-72f18694-5c70-4df3-bd08-52f5b4b1e7f9.png)

O buscar otra solucion que ahora no se me ocurre. Tambien podríamos dejarlo asi suponiendo que la mayoría de los celus manejan resoluciones mas grande, pero no lo se.

El resto me parece que está perfecto.

2022-05-01 20:35 UTC, BrenMiRo commented
> Parece que según la resolución de la pantalla el texto puede quedar muy cerca del borde
> Podriamos acercar el texto al icono
> achicarle la letra
> O buscar otra solucion que ahora no se me ocurre. Tambien podríamos dejarlo asi suponiendo que la mayoría de los celus manejan resoluciones mas grande, pero no lo se.
> El resto me parece que está perfecto.

#### Listo! Achique la letra y le reduje un poco el margen al icono y al titulo

2022-05-01 20:36 UTC, merged